Update to rspec 3 from 2 to resolve exists error
To resolve the following error:
rspec-core-2.14.6/lib/rspec/core/ruby_project.rb:27:in `block in
find_first_parent_containing': undefined method `exists?' for class File
(NoMethodError)

        ascend_until {|path| File.exists?(File.join(path, dir))}
                                    ^^^^^^^^
Did you mean?  exist?

I ran bundle update rspec and updated the spec_helper.rb file to use the
new syntax for color (from `config.color_enabled` to `config.color`) and
this resolved the error.  There are still many deprecation warnings
which will need to be resolved in the future, but the tests are now
running/passing.